apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: bootnode1
  labels:
    component: bootnode
spec:
  replicas: 1
  selector:
    matchLabels:
      component: bootnode
  template:
    metadata:
      labels:
        component: bootnode
    spec:
      containers:
        - name: bootnode
          image: ethereum/client-go:alltools-v1.7.3
          ports: 
            - containerPort: 8545
              name: rpc
            - containerPort: 30303
              name: discovery-tcp
              protocol: TCP
            - containerPort: 30303
              name: discovery-udp
              protocol: UDP
            - containerPort: 30301
              name: bootnode-udp
              protocol: UDP
          command: ["bootnode"]
          args: 
            - "--nodekey=/opt/bootnode/boot.key"
            - "--verbosity=9"
          volumeMounts:
            - name: bootkey
              mountPath: "/opt/bootnode"
              readOnly: true
      volumes:
        - name: bootkey
          secret:
            secretName: bootkey1
---
kind: Service
apiVersion: v1
metadata:
  name: bootnode
spec:
  selector:
    component: bootnode
  ports:
    - port: 8545
      targetPort: 8545
      name: rpc
      protocol: TCP
    - port: 30303
      targetPort: 30303
      name: discovery-tcp
      protocol: TCP
    - port: 30303
      targetPort: 30303
      name: discovery-udp
      protocol: UDP
    - port: 30301
      targetPort: 30301
      name: bootnode-udp
      protocol: UDP
