kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: ethstats
  labels:
    component: ethstats
spec:
  replicas: 1
  selector:
    matchLabels:
      component: ethstats
  template:
    metadata:
      labels:
        component: ethstats
    spec:
      containers:
        - name: ethstats
          image: ethereumex/eth-netstats:latest
          command: ["npm"]
          args: ["start"]
          ports: 
            - containerPort: 3000
              name: web
          env:
            - name: WS_SECRET
              value: secret
---
kind: Service
apiVersion: v1
metadata:
  name: ethstats
spec:
  selector:
    component: ethstats
  ports:
    - port: 3000
      targetPort: 3000
